# Generated by Django 2.2.13 on 2020-06-12 20:31

import datetime
from django.db import migrations, models
import djongo.models.fields
import enumfields.fields
import smg.modelfields
import smg.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', enumfields.fields.EnumField(enum=smg.models.JobStatus, max_length=17)),
                ('result', smg.modelfields.EmbeddedDictField(model_container=dict, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
